modLoader="javafml"
loaderVersion="[35,)"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/LiskoSlayer63/garbagebins/issues"

[[mods]]
modId="garbagebins"
version="2.0.3"

displayName="Garbage Bins"
displayURL="https://www.curseforge.com/minecraft/mc-mods/trashcans-reborn"
logoFile="garbagebins.png"
authors="LiskoSlayer63"

description='''
Simple garbage bins for items and fluids.
'''

[[dependencies.garbagebins]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.garbagebins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
